// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDLaMrkYIJLdroPg7d-qJnHGqCXAVuaA',
    appId: '1:226150220577:web:55f6752629ac9b28d5b460',
    messagingSenderId: '226150220577',
    projectId: 'flutterauth-1eb6f',
    authDomain: 'flutterauth-1eb6f.firebaseapp.com',
    storageBucket: 'flutterauth-1eb6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRXxxIIQSdCOUuJskOsVYxsiUK7Zdc3SQ',
    appId: '1:226150220577:android:854506184ffb1b71d5b460',
    messagingSenderId: '226150220577',
    projectId: 'flutterauth-1eb6f',
    storageBucket: 'flutterauth-1eb6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPxRCIzcsOpoac1ucyutGavFnr-wLXApU',
    appId: '1:226150220577:ios:7e53836e3bdd43e1d5b460',
    messagingSenderId: '226150220577',
    projectId: 'flutterauth-1eb6f',
    storageBucket: 'flutterauth-1eb6f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPxRCIzcsOpoac1ucyutGavFnr-wLXApU',
    appId: '1:226150220577:ios:8d369002174c5825d5b460',
    messagingSenderId: '226150220577',
    projectId: 'flutterauth-1eb6f',
    storageBucket: 'flutterauth-1eb6f.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
